### ISSUE TITLE
compatibility with Hyprbars

### ISSUE THREAD

**Issue by BangL** [micha4w/Hypr-DarkWindow#9]
sadly, the invertion also gets applied to added window decorations by the Hyprbars plugin:

![image](https://github.com/user-attachments/assets/54f3946b-0e25-42b7-a2d8-63d3d5b76d0d)

any way to add an exception for those? :D

**Comment by micha4w** [comment]
Thanks for your research, but sadly it isn't that easy. Since decorations are a Hyprland feature and are not separate Windows. Instead they are drawn right before or after  the Window itself, with just a few lines of code in between them, and i haven't seen an easy way to hook into the code between the 2 draw calls:
https://github.com/hyprwm/Hyprland/blob/6e0aadc585c6d9fdaaebfa5853adbf9610897c82/src/render/Renderer.cpp#L644-L674

It would be easy if we could hook into `IHyprWindowDecoration::draw` using Hyprlands hook system, but hooking a pure virtual function seems to not be possible.

If you have know of a way I would be happy to hear!

**Comment by micha4w** [comment]
I ended up finding a not too hacky way: Create a Class thats wraps IHyprDecorations and then wrap all decorations everytime the window is rendered.

https://github.com/micha4w/Hypr-DarkWindow/blob/264130cb07d40cc20e791d68cd1811ec822bf401/src/DecorationsWrapper.h#L5-L35
https://github.com/micha4w/Hypr-DarkWindow/blob/264130cb07d40cc20e791d68cd1811ec822bf401/src/WindowInverter.cpp#L18-L24

It worked quite well in my testing, i pushed it to tag v0.44.1

**Comment by micha4w** [comment]
I'll be closing this issue since you seem to be happy!

**Comment by micha4w** [comment]
Reopening this because if you are using window rules and `decoration::drop_shadow = true` it will segfault, working on a fix, but for now the easiest fix is to just turn off drop_shadows

**Comment by micha4w** [comment]
Should be fixed now, i moved the v0.44.1 tag to the new version
